taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10

logging:
  level:
    org.springframework.security: debug

spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud

  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9000/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
            issuer-uri: http://authserver:9000
            authorization-uri: http://authserver:9000/oauth2/authorize
            token-uri: http://authserver:9000/oauth2/token
            jwk-set-uri: http://authserver:9000/oauth2/jwks
            user-info-uri: http://authserver:9000/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: http://authserver:9000/oauth2/jwks
    user:
      name: qwerty
      password: 1234
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
