spring:
  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate
      local-datacenter: datacenter1


#jdbc:h2:mem:tacocloud

    #datasource:
    #generate-unique-name: false
    #name: tacocloud